title: ViTAL Lab
subtitle: Computational Behavior and Health Analytics
description: Computational Beha**Vi**or and Heal**T**h **A**na**L**ytics (**ViTAL**) Lab at Emory Biomedical Informatics strives to develop artificial intelligence (AI) systems that are inclusive, accessible, fair, and reliable that will effectively improve the healthcare system. Our mission is to develop Ubiquitous Computing, Computer Vision, and Machine Learning systems using distributed ambient, mobile, and wearable devices to monitor patients' conditions in hospitals or everyday life. We are also invested in deploying and testing the developed AI systems in real-world clinical and daily living environments actively collaborating with stakeholders in healthcare.
header: null
footer: null
header-dark: false
footer-dark: false
links:
  email: hyeokhyen.kwon@emory.edu
  orcid: 0000-0002-5693-3278
  google-scholar: OwLXC4YAAAAJ
  github: KwonVitalLab
  twitter: HyeokhyenKwon
  # youtube: null
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: hyeokhyen.kwon@emory.edu
github: KwonVitalLab
twitter: KwonVitalLab
# youtube: KwonVitalLab
