title: ViTAL Lab
subtitle: Machine Learning for Behavior and Health Analytics
description: We strive to develop artificial intelligence system that is inclusive, accessible, fair, and reliable that will effectively improve healthcare system. Our mission is to tackle mental and brain helth challenges through the developement of efficient computing and machine learning system on the network edge using distributed ambient, mobile, and edge devices to monitor patients' behaviors in everyday life. 
header: null
footer: null
header-dark: false
footer-dark: false
links:
  email: hyeokhyen.kwon@emory.edu
  orcid: 0000-0002-5693-3278
  google-scholar: OwLXC4YAAAAJ
  github: KwonVitalLab
  twitter: HyeokhyenKwon
  # youtube: null
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: hyeokhyen.kwon@emory.edu
github: KwonVitalLab
twitter: KwonVitalLab
# youtube: KwonVitalLab
