# Plos Digital Health - Trisha Mobile Vision Simulated Gait Impairment
- id: doi:10.1371/journal.pdig.0001004
  image: https://KwonVitalLab.github.io/images/publications/arXiv-2412.01056.jpg

# medRxiv - Kitchen x wearable
- id: doi:10.1101/2025.05.24.25328107
  image: https://KwonVitalLab.github.io/images/publications/Overview_Pipeline-kitchenXwearable.png

# medRxiv - Kitchen x open-shelving
- id: doi:10.1080/26892618.2025.2576213
  image: https://KwonVitalLab.github.io/images/publications/Kitchen_Space_Image.jpg

# medRxiv - taVNS Dancing
- id: doi:10.1101/2025.05.23.25327218
  image: https://KwonVitalLab.github.io/images/publications/doi-10.1101-2025.05.23.25327218.png

# LLM Depression Review:
- id: doi:10.1145/3673906

# Digital Twin - EP6 Multi-beacon BLE
- id: doi:10.1049/dgt2.70001

# DADM - CEP Vision-only MoCA
- id: doi:10.1002/dad2.70085
  image: https://KwonVitalLab.github.io/images/publications/cep_ep6_vision_only_moca.png

# Ariv - FOG x Wearable X Fair
- id: arXiv:2502.09626
  image: https://KwonVitalLab.github.io/images/publications/arxiv-2502.09626.png

# Ali Bharami Rad - Wearable x Autism 
- id: doi:10.1088/1361-6579/ada51b

# Abmed Abbasi - LLM x Depression
- id: doi:10.1145/3673906

# Arxiv - MGH x MCI x Zoom
- id: arxiv:2412.14194
  image: https://KwonVitalLab.github.io/images/publications/arXiv-2412.14194.PNG

# Arxiv - TCFD Vision - Group & Binary
- id: arxiv:2407.21691
  image: https://KwonVitalLab.github.io/images/publications/tcfd-vision-group-binary.png

# Sensors - Tremor in Clinics (Lucas)
- id: doi:10.3390/s24154960
  image: https://KwonVitalLab.github.io/images/publications/tremor_in_clinics.png

# Plos Digital Health
- id: doi:10.1371/journal.pdig.0000413
  image: https://KwonVitalLab.github.io/images/publications/multi-modal-MH-fair.png

# IMUGPT 2.0
- id: doi:10.1145/3678545
  image: https://KwonVitalLab.github.io/images/publications/imugpt-imwut-2024-02.png

# J-ISPIN 2024 - CEP-EP6 Group Localization
- id: doi:10.1109/JISPIN.2024.3354248
  image: https://KwonVitalLab.github.io/images/publications/grp-loc.png
  buttons:
    - type: website
      link: https://github.com/cliffordlab/GroupPositionFromCamera

# GenAI4PC
- id: arxiv:2310.12085
  image: https://KwonVitalLab.github.io/images/publications/genai4pc.png

# ASSET 2023 - FingerSpeller
- id: doi:10.1145/3597638.3614491
  image: https://KwonVitalLab.github.io/images/publications/fingerspelling.png

# JBHI 2023 - Multimodal mental health assessment
- id: doi:10.1109/JBHI.2024.3352075
  image: https://KwonVitalLab.github.io/images/publications/multi-modal-MH.png

# Sensors 2023 - Subtype
- id: doi:10.3390/s23198330
  image: https://KwonVitalLab.github.io/images/publications/aan_subtype_2023.png

# ISWC 2023 IMUGPT
- id: doi:10.1145/3594738.3611361
  image: https://KwonVitalLab.github.io/images/publications/gpt-iswc.png
  buttons:
    - type: website
      link: https://github.com/ZikangLeng/IMUGPT
  tags: 
    - 🏆 Best Paper Finalist and Honorable Mention in Ubicomp/ISWC 2023

# ISWC 2023 IMUTube Subtle
- id: doi:10.1145/3594738.3611364
  image: https://KwonVitalLab.github.io/images/publications/motion_subtlety_index.png

# WiFi Academic performance
- id: doi:10.1140/epjds/s13688-023-00398-2
  image: https://KwonVitalLab.github.io/images/publications/wifi_community.png

# Sensor CEP-EP6 BLE-IMU-based Tracking
- id: doi:10.3390/s23239517
  image: https://KwonVitalLab.github.io/images/publications/cep_ep6_ble_imu_mot.png

# J-ISPIN CEP-EP6 Camera-based Tracking
- id: doi:10.1109/JISPIN.2023.3337189
  image: https://KwonVitalLab.github.io/images/publications/cep_ep6_camera_mot.png

# AAN - FOG
- id: doi:10.1212/WNL.0000000000203857
  image: https://KwonVitalLab.github.io/images/publications/aan_fog_2023.png
  publisher: Neurology

# AAN - Subtype
- id: doi:10.1212/WNL.0000000000203887
  image: https://KwonVitalLab.github.io/images/publications/aan_subtype_2023.png
  publisher: Neurology

# Sensors 2023 XAI4FOG
- id: doi:10.3390/s23041766
  image: https://KwonVitalLab.github.io/images/publications/xai4fog.png
  tags: 
    - 🏆 Finalist for the Oracle for Research Fellows program
    - 🏆 Oracle for Research Project Award

# ISWC 2022 IMUTube Subtle
- id: doi:10.1145/3544793.3560337
  image: https://KwonVitalLab.github.io/images/publications/motion_subtlety_index.png

# GetMobile IMUTube
- id: doi:10.1145/3486880.3486891
  title: "Can You See It? Good, So We Can Sense It!"
  image: https://KwonVitalLab.github.io/images/publications/getmobile.png

# IJCAI Workshop 2021
- id: doi:10.1007/978-981-16-0575-8_4
  image: https://KwonVitalLab.github.io/images/publications/ijcai_workshop.png
  publisher: Deep Learning for Human Activity Recognition Second International Workshop, DL-HAR 2020, Held in Conjunction with IJCAI-PRICAI 2020

# IMWUT 21 IMUTube v3
- id: doi:10.3390/s21248337
  image: https://KwonVitalLab.github.io/images/publications/complexDLIMUTube.png

# IMWUT 21 IMUTube v2
- id: doi:10.1145/3478096
  title: "Approaching the real-world: Supporting activity recognition training with virtual imu data"
  image: https://KwonVitalLab.github.io/images/publications/imutube_v2.png
  buttons:
    - type: website
      link: https://github.com/hyeokhyen/imutube
  tags:
    - 🏆 Finalist for Gaetano Borriello Outstanding Student Award at Ubicomp 2021

# IMWUT 20 IMUTube v1
- id: doi:10.1145/3411841
  title: "IMUTube: Automatic Extraction of Virtual on-body Accelerometry from Video for Human Activity Recognition."
  image: https://KwonVitalLab.github.io/images/publications/IMUTube Diagrams.jpg
  buttons:
    - type: website
      link: https://github.com/hyeokhyen/imutube
  tags: 
    - 🏆 Oracle for Research Project Award
    - 💡 Patent published.

# ISWC 19 labeljitter
- id: doi:10.1145/3341163.3347744
  image: https://KwonVitalLab.github.io/images/publications/label jitter.png
  buttons:
    - type: website
      link: https://github.com/hyeokhyen/sat

# ISWC 18 Structural ECDF
- id: doi:10.1145/3267242.3267258
  image: https://KwonVitalLab.github.io/images/publications/structECDF.png
  buttons:
    - type: website
      link: https://github.com/hyeokhyen/structecdf

# ICCV 2015 Hyperspectral
- id: doi:10.1109/ICCV.2015.43
  image: https://KwonVitalLab.github.io/images/publications/iccv15.png
      
# CVPR 2015 Depth map
- id: doi:10.1109/CVPR.2015.7298611
  image: https://KwonVitalLab.github.io/images/publications/cvpr15.png
